<?php
/**
 * @author Anton Gorlanov <antonxacc@gmail.com>
 *
 * Message result with log of deploying project configs
 * This is generated by deploy service and is processed by rds service
 */
namespace whotrades\RdsSystem\Message;

class ProjectConfigResult extends Base
{
    public $projectConfigHistoryId = null;
    public $log = null;

    /**
     * ProjectConfigResult constructor.
     *
     * @param int $projectConfigHistoryId
     * @param string $log
     */
    public function __construct($projectConfigHistoryId, $log)
    {
        $this->projectConfigHistoryId = $projectConfigHistoryId;
        $this->log = $log;

        parent::__construct();
    }
}
